package com.projectnexus.tasks.domain;

import com.projectnexus.common.entity.BaseTenantEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Cross-team task that can be linked to a Data Contract, Payload, or Deviation.
 *
 * <p>Tasks support Kanban-style workflow management with status transitions:
 * TODO → IN_PROGRESS → IN_REVIEW → DONE.
 *
 * <p>Tasks can be created manually or generated by the AI Task Suggester
 * when deviations are detected during payload ingestion.
 */
@Entity
@Table(name = "tasks", indexes = {
        @Index(name = "idx_tasks_tenant_status", columnList = "tenant_id, status"),
        @Index(name = "idx_tasks_tenant_assignee", columnList = "tenant_id, assignee_id"),
        @Index(name = "idx_tasks_linked", columnList = "linked_to_type, linked_to_id")
})
@Getter
@Setter
@NoArgsConstructor
public class Task extends BaseTenantEntity {

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TaskStatus status = TaskStatus.TODO;

    @Column(name = "assignee_id")
    private UUID assigneeId;

    @Column(name = "due_date")
    private LocalDateTime dueDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "linked_to_type", length = 20)
    private LinkType linkedToType;

    @Column(name = "linked_to_id")
    private UUID linkedToId;

    @Column(name = "ai_generated", nullable = false)
    private boolean aiGenerated = false;

    /**
     * Transitions the task to a new status with basic workflow validation.
     */
    public void transitionTo(TaskStatus newStatus) {
        if (this.status == TaskStatus.DONE && newStatus != TaskStatus.DONE) {
            throw new IllegalStateException("Cannot reopen a completed task");
        }
        this.status = newStatus;
    }
}
